### ISSUE TITLE
Can this package get converted to native dart 

### ISSUE THREAD

**Issue by guyluz11** [DirectMyFile/upnp.dart#20]
I was wondering if this package or part of it can get converted to native dart and thus work on all platforms, can get executed from the server-side as well?.

What part of this library requires the flutter framework and what part of it only required native dart code.

**Comment by moda20** [comment]
this works for native dart. it can also be used for flutter too. so no need for any changes for your case

**Comment by guyluz11** [comment]
Thanks @moda20, maybe I got confused with another package.
